"""
M24.2 — Mayasari Bakery Customer Insight Framework.

Defines the business questions and evidence requirements used
by the customer insight engine.

This module intentionally contains framework definitions only.
No analytics calculations are performed here.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import Final


@dataclass(frozen=True)
class InsightDefinition:
    """Definition of one customer business insight."""

    insight_id: str
    title: str
    business_question: str
    category: str
    required_columns: tuple[str, ...]
    evidence_metrics: tuple[str, ...]
    interpretation_rule: str
    recommended_action: str


CUSTOMER_INSIGHT_FRAMEWORK: Final[
    tuple[InsightDefinition, ...]
] = (
    InsightDefinition(
        insight_id="customer_value_concentration",
        title="Customer Value Concentration",
        business_question=(
            "How concentrated is annualized customer value "
            "among the highest-value customers?"
        ),
        category="Customer Economics",
        required_columns=(
            "customer_id",
            "annualized_clv",
            "clv_tier",
        ),
        evidence_metrics=(
            "total_annualized_clv",
            "top_10_clv",
            "top_25_clv",
            "top_10_clv_share",
            "top_25_clv_share",
            "platinum_clv_share",
        ),
        interpretation_rule=(
            "Higher concentration indicates greater economic "
            "dependency on a smaller group of customers."
        ),
        recommended_action=(
            "Protect high-value customer relationships while "
            "developing lower-tier customers to reduce dependency."
        ),
    ),
    InsightDefinition(
        insight_id="clv_tier_economics",
        title="CLV Tier Economics",
        business_question=(
            "How much customer value is generated by each "
            "CLV tier?"
        ),
        category="Customer Economics",
        required_columns=(
            "customer_id",
            "annualized_clv",
            "historical_clv",
            "clv_tier",
        ),
        evidence_metrics=(
            "tier_customer_count",
            "tier_customer_share",
            "tier_annualized_clv",
            "tier_clv_share",
            "tier_average_annualized_clv",
        ),
        interpretation_rule=(
            "A tier's economic importance depends on both "
            "its customer population and its CLV contribution."
        ),
        recommended_action=(
            "Use differentiated retention and development "
            "strategies according to customer economic value."
        ),
    ),
    InsightDefinition(
        insight_id="rfm_customer_quality",
        title="RFM Customer Quality",
        business_question=(
            "What does observed recency, frequency, and monetary "
            "behavior indicate about the customer base?"
        ),
        category="Customer Behavior",
        required_columns=(
            "customer_id",
            "recency",
            "frequency",
            "monetary",
            "rfm_score",
            "rfm_total",
            "segment",
        ),
        evidence_metrics=(
            "segment_customer_count",
            "segment_customer_share",
            "segment_revenue",
            "segment_gross_profit",
            "segment_average_rfm",
        ),
        interpretation_rule=(
            "RFM segments describe observed customer behavior "
            "and should not be interpreted as causal drivers."
        ),
        recommended_action=(
            "Match engagement strategy to observed customer "
            "behavior rather than applying one strategy to all customers."
        ),
    ),
    InsightDefinition(
        insight_id="customer_opportunity_priority",
        title="Customer Opportunity Priority",
        business_question=(
            "Which customer opportunity groups deserve the most "
            "immediate management attention?"
        ),
        category="Customer Opportunity",
        required_columns=(
            "customer_id",
            "annualized_clv",
            "clv_tier",
            "segment",
            "opportunity",
            "opportunity_priority",
            "priority_rationale",
        ),
        evidence_metrics=(
            "opportunity_customer_count",
            "opportunity_customer_share",
            "opportunity_annualized_clv",
            "opportunity_clv_share",
            "priority_group_clv_share",
        ),
        interpretation_rule=(
            "Priority should combine economic value with observed "
            "customer behavior and the predefined opportunity classification."
        ),
        recommended_action=(
            "Prioritize economically meaningful intervention groups, "
            "especially high-value customers showing declining engagement."
        ),
    ),
    InsightDefinition(
        insight_id="rescue_economics",
        title="Rescue Customer Economics",
        business_question=(
            "How much customer value is associated with customers "
            "classified as Rescue?"
        ),
        category="Customer Opportunity",
        required_columns=(
            "customer_id",
            "annualized_clv",
            "historical_clv",
            "clv_tier",
            "segment",
            "opportunity",
            "opportunity_priority",
        ),
        evidence_metrics=(
            "rescue_customer_count",
            "rescue_customer_share",
            "rescue_annualized_clv",
            "rescue_clv_share",
            "rescue_average_clv",
            "rescue_platinum_count",
        ),
        interpretation_rule=(
            "Rescue customers represent an intervention opportunity "
            "because their classification combines customer economics "
            "with declining engagement."
        ),
        recommended_action=(
            "Prioritize targeted re-engagement where expected customer "
            "economic value justifies intervention."
        ),
    ),
    InsightDefinition(
        insight_id="high_value_at_risk",
        title="High-Value At-Risk Customers",
        business_question=(
            "Are high-value customers exposed to elevated retention risk "
            "based on the existing opportunity classification?"
        ),
        category="Retention",
        required_columns=(
            "customer_id",
            "annualized_clv",
            "clv_tier",
            "segment",
            "opportunity",
            "recency",
            "rfm_total",
        ),
        evidence_metrics=(
            "at_risk_customer_count",
            "at_risk_annualized_clv",
            "at_risk_clv_share",
            "at_risk_platinum_count",
            "at_risk_gold_count",
        ),
        interpretation_rule=(
            "At-risk classification reflects observed customer behavior "
            "and the project's existing segmentation logic."
        ),
        recommended_action=(
            "Protect high-value at-risk relationships with targeted "
            "retention actions before broad acquisition spending."
        ),
    ),
    InsightDefinition(
        insight_id="customer_profitability",
        title="Customer Profitability",
        business_question=(
            "How does customer value translate into gross-profit contribution?"
        ),
        category="Customer Economics",
        required_columns=(
            "customer_id",
            "revenue",
            "gross_profit",
            "gross_margin_pct",
            "historical_clv",
            "annualized_clv",
        ),
        evidence_metrics=(
            "total_revenue",
            "total_gross_profit",
            "overall_gross_margin",
            "top_customer_profit_share",
            "average_customer_gross_profit",
        ),
        interpretation_rule=(
            "Customer economic value should be interpreted through "
            "gross-profit contribution as well as revenue."
        ),
        recommended_action=(
            "Prioritize customers and segments based on profitable "
            "economic contribution rather than revenue alone."
        ),
    ),
)


def validate_framework(
    framework: tuple[InsightDefinition, ...] = CUSTOMER_INSIGHT_FRAMEWORK,
) -> None:
    """Validate framework structure and uniqueness."""

    if not framework:
        raise ValueError("Customer insight framework is empty.")

    insight_ids = [
        definition.insight_id
        for definition in framework
    ]

    if len(insight_ids) != len(set(insight_ids)):
        raise ValueError(
            "Customer insight framework contains duplicate insight IDs."
        )

    for definition in framework:
        if not definition.insight_id:
            raise ValueError("Insight ID cannot be empty.")

        if not definition.title:
            raise ValueError(
                f"Insight title is empty: {definition.insight_id}"
            )

        if not definition.business_question:
            raise ValueError(
                f"Business question is empty: {definition.insight_id}"
            )

        if not definition.required_columns:
            raise ValueError(
                f"Required columns are empty: {definition.insight_id}"
            )

        if not definition.evidence_metrics:
            raise ValueError(
                f"Evidence metrics are empty: {definition.insight_id}"
            )

        if not definition.interpretation_rule:
            raise ValueError(
                f"Interpretation rule is empty: {definition.insight_id}"
            )

        if not definition.recommended_action:
            raise ValueError(
                f"Recommended action is empty: {definition.insight_id}"
            )


def print_framework(
    framework: tuple[InsightDefinition, ...] = CUSTOMER_INSIGHT_FRAMEWORK,
) -> None:
    """Print the customer insight framework."""

    validate_framework(framework)

    print("=" * 100)
    print("M24.2 — CUSTOMER BUSINESS INSIGHT FRAMEWORK")
    print("=" * 100)

    print(
        f"\nInsight definitions: {len(framework)}"
    )

    for index, definition in enumerate(
        framework,
        start=1,
    ):
        print(
            f"\n[{index}] {definition.insight_id}"
        )
        print(
            f"Title              : {definition.title}"
        )
        print(
            f"Category           : {definition.category}"
        )
        print(
            f"Business question  : {definition.business_question}"
        )
        print(
            "Required columns   : "
            + ", ".join(definition.required_columns)
        )
        print(
            "Evidence metrics   : "
            + ", ".join(definition.evidence_metrics)
        )
        print(
            f"Interpretation     : {definition.interpretation_rule}"
        )
        print(
            f"Recommended action : {definition.recommended_action}"
        )

    print("\n" + "=" * 100)
    print("M24.2 FRAMEWORK VALID")
    print("=" * 100)


if __name__ == "__main__":
    print_framework()
